apiVersion: v2
name: product-service
description: A Helm chart for Product Service microservice
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - product
  - microservice
  - fastapi
  - python
maintainers:
  - name: Zashita LTD
    email: dev@zashita.ltd
dependencies:
  - name: postgresql
    version: "13.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "18.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    version: "26.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
